// <auto-generated />
using System;
using DataServices.Migrations.EntityModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataServices.Migrations.Migrations
{
    [DbContext(typeof(DataServiceContext))]
    [Migration("20200618162456_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataServices.Migrations.EntityModel.CRMProgram", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Hours")
                        .IsRequired()
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime?>("ModiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Code", "ConfirmationCode");

                    b.HasIndex("ConfirmationCode");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CRMProgram");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Confirmation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CompanyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("Confirmations");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CRMProgramCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRMProgramCode1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CRMProgramConfirmationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("ModiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("StarDate")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Tag")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationCode");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("CRMProgramCode1", "CRMProgramConfirmationCode");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.CRMProgram", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModel.Confirmation", "Confirmation")
                        .WithMany("Programs")
                        .HasForeignKey("ConfirmationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModel.Employee", "Employee")
                        .WithMany("Programs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Confirmation", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModel.Company", "Company")
                        .WithMany("Confirmations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModel.Task", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModel.Confirmation", "Confirmation")
                        .WithMany("Tasks")
                        .HasForeignKey("ConfirmationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModel.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModel.CRMProgram", "CRMProgram")
                        .WithMany("Tasks")
                        .HasForeignKey("CRMProgramCode1", "CRMProgramConfirmationCode");
                });
#pragma warning restore 612, 618
        }
    }
}
