// <auto-generated />
using System;
using DataServices.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataServices.Migrations.Migrations
{
    [DbContext(typeof(DataServiceContext))]
    [Migration("20200624094548_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataServices.Migrations.EntityModels.CRMProgram", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Code", "ConfirmationCode");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ConfirmationCode");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CRMProgram");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Confirmation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("Confirmation");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CRMProgramCode")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("StarDate")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationCode");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("CRMProgramCode", "ConfirmationCode");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.CRMProgram", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModels.Company", "Company")
                        .WithMany("CRMPrograms")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModels.Confirmation", "Confirmation")
                        .WithMany("CRMPrograms")
                        .HasForeignKey("ConfirmationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModels.Employee", "Employee")
                        .WithMany("CRMPrograms")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Confirmation", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModels.Company", "Company")
                        .WithMany("Confirmations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServices.Migrations.EntityModels.Task", b =>
                {
                    b.HasOne("DataServices.Migrations.EntityModels.Confirmation", "Confirmation")
                        .WithMany("Tasks")
                        .HasForeignKey("ConfirmationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServices.Migrations.EntityModels.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("DataServices.Migrations.EntityModels.CRMProgram", "CRMProgram")
                        .WithMany("Tasks")
                        .HasForeignKey("CRMProgramCode", "ConfirmationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
